### ISSUE TITLE
Export common keycodes

### ISSUE THREAD

**Issue by chrislaughlin** [chrislaughlin/react-short-keys#3]
Export common keyCodes along with the default KeyPress component export. 

e.g. 
```
export default Keypress;
export {
    ARROW_UP,
    ARROW_DOWN,
    ARROW_LEFT,
    ARROW_RIGHT
}
```

```
import KeyPress, { ARROW_LEFT, ARROW_RIGHT } from 'react-short-keys';
```

**Comment by salilgupta2510** [comment]
@chrislaughlin  
i ll do it.

**Comment by chrislaughlin** [comment]
@salilgupta2510 Its all yours

**Comment by salilgupta2510** [comment]
@chrislaughlin 
can you elaborate a bit, what exact changes you require ?

**Comment by chrislaughlin** [comment]
I think it would be useful to export some common used key codes as named variables. As the component takes in an array of keys to trigger on the consumer needs to provide the key codes. However this relies on the consumer to know the key codes. I was thinking something like this:

```
//src/index.js
import { ARROW_LEFT, ARROW_RIGHT, ARROW_UP, ARROW_DOWN } from 'objects/commonCodes';

......
export default KeyPress;
export { ARROW_LEFT, ARROW_RIGHT, ARROW_UP, ARROW_DOWN };
```

```
//objects/commonCodes.js

export const ARROW_LEFT = 37;
export const ARROW_RIGHT = 39;
export const ARROW_UP= 38;
export const ARROW_DOWN = 40;
```

Then in useage:

```
import KeyPress { ARROW_LEFT, ARROW_RIGHT } from 'react-short-keys';

......


<KeyPress
    onKeys={[ARROW_LEFT, ARROW_RIGHT]}
    onKeyPress={someFucn}
/>
```

**Comment by mbaranovski** [comment]
@salilgupta2510 please let me know if you're working on that, if not I'm happy to take it over as my first Open Source contribution.

**Comment by chrislaughlin** [comment]
@bombellos this has been done already.
